/**
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject.ui.contentassist;

import fr.polytech.nice.elliot.sle.sensorproject.ui.contentassist.AbstractSPDSLProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SPDSLProposalProvider extends AbstractSPDSLProposalProvider {
}
