/*
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class SPDSLRuntimeModule extends AbstractSPDSLRuntimeModule {
}
