/**
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject.ide;

import fr.polytech.nice.elliot.sle.sensorproject.ide.AbstractSPDSLIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class SPDSLIdeModule extends AbstractSPDSLIdeModule {
}
