/**
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.polytech.nice.elliot.sle.sensorproject.SPDSLRuntimeModule;
import fr.polytech.nice.elliot.sle.sensorproject.SPDSLStandaloneSetup;
import fr.polytech.nice.elliot.sle.sensorproject.ide.SPDSLIdeModule;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class SPDSLIdeSetup extends SPDSLStandaloneSetup {
  @Override
  public Injector createInjector() {
    SPDSLRuntimeModule _sPDSLRuntimeModule = new SPDSLRuntimeModule();
    SPDSLIdeModule _sPDSLIdeModule = new SPDSLIdeModule();
    return Guice.createInjector(Modules2.mixin(_sPDSLRuntimeModule, _sPDSLIdeModule));
  }
}
