/**
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject.validation;

import fr.polytech.nice.elliot.sle.sensorproject.validation.AbstractSPDSLValidator;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class SPDSLValidator extends AbstractSPDSLValidator {
}
