/**
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject.ui;

import fr.polytech.nice.elliot.sle.sensorproject.ui.AbstractSPDSLUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class SPDSLUiModule extends AbstractSPDSLUiModule {
  public SPDSLUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
