/**
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject;

import fr.polytech.nice.elliot.sle.sensorproject.AbstractSPDSLRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class SPDSLRuntimeModule extends AbstractSPDSLRuntimeModule {
}
