/**
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject;

import fr.polytech.nice.elliot.sle.sensorproject.SPDSLStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class SPDSLStandaloneSetup extends SPDSLStandaloneSetupGenerated {
  public static void doSetup() {
    new SPDSLStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
