/*
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject.parser.antlr;

import com.google.inject.Inject;
import fr.polytech.nice.elliot.sle.sensorproject.parser.antlr.internal.InternalSPDSLParser;
import fr.polytech.nice.elliot.sle.sensorproject.services.SPDSLGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class SPDSLParser extends AbstractAntlrParser {

	@Inject
	private SPDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalSPDSLParser createParser(XtextTokenStream stream) {
		return new InternalSPDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "System";
	}

	public SPDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(SPDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
