/*
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SPDSLAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/polytech/nice/elliot/sle/sensorproject/parser/antlr/internal/InternalSPDSL.tokens");
	}
}
