/*
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject.ide


/**
 * Use this class to register ide components.
 */
class SPDSLIdeModule extends AbstractSPDSLIdeModule {
}
