/**
 * generated by Xtext 2.14.0
 */
package fr.polytech.nice.elliot.sle.sensorproject.scoping;

import fr.polytech.nice.elliot.sle.sensorproject.scoping.AbstractSPDSLScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class SPDSLScopeProvider extends AbstractSPDSLScopeProvider {
}
